# Generated by Django 2.1.7 on 2019-10-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20190922_2033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section_name', 'semester', 'course')},
        ),
    ]
